hw7/socialnetwork/urls.py
from django.urls import path
from socialnetwork import views

urlpatterns = [
    path('', views.global_stream_action, name='home'),
    path('global_stream', views.global_stream_action, name='global_stream'),
    path('follower_stream', views.follower_stream_action, name='follower_stream'),
    path('login', views.login_action, name='login'),
    path('logout', views.logout_action, name='logout'),
    path('register', views.register_action, name='register'),
    path('my_profile', views.my_profile_action, name='my_profile'),
    path('personal_profile/<int:id>', views.personal_profile_action, name='personal_profile'),
    path('photo/<int:id>', views.get_photo_action, name='photo'),
    path('get-global', views.json_dumps_serializer_global, name='get-global'),
    path('get-follower', views.json_dumps_serializer_follower, name='get-follower'),
    path('add-comment', views.add_comment, name='add-comment'),

]

hw7/webapps/urls.py
from django.urls import path, include
from socialnetwork import urls as socialnetwork_urls
from socialnetwork import views as socialnetwork_views
urlpatterns = [
    path('', socialnetwork_views.global_stream_action),
    path('socialnetwork/', include(socialnetwork_urls))
]

hw7/socialnetwork/models.py
from django.db import models
from django.contrib.auth.models import User
# from django.contrib.auth.models import AbstractUser
from django.utils import timezone
from urllib.parse import urlencode

from rest_framework import status, serializers
from rest_framework.views import APIView
from rest_framework.response import Response

class Client(models.Model):
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    followings = models.ManyToManyField(User, related_name='followings')


class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.PROTECT)
    content = models.CharField(max_length=10000)
    date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f'id={self.id}, content="{self.content}"'


class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.PROTECT)
    content = models.CharField(max_length=10000)
    date = models.DateTimeField(default=timezone.now)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    def __str__(self):
        return f'id={self.id}, content="{self.content}"'


class Profile(models.Model):
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    bio = models.CharField(max_length=10000, blank=True)
    profile_picture = models.FileField(blank=True)
    content_type = models.CharField(max_length=50, default='jpg')

    def __str__(self):
        return f'id={self.id}, content="{self.bio}"'

hw7/socialnetwork/forms.py
from django import forms

from django.contrib.auth.models import User
from django.contrib.auth import authenticate

from socialnetwork.models import Profile, Post


class LoginForm(forms.Form):
    username = forms.CharField(max_length=20)
    password = forms.CharField(max_length=20, widget=forms.PasswordInput)

    def clean(self):
        cleaned_data = super().clean()
        username = cleaned_data["username"]
        password = cleaned_data["password"]
        user = authenticate(username=username, password=password)
        if not user:
            raise forms.ValidationError("Invalid username/password")
        return cleaned_data


class RegisterForm(forms.Form):
    first_name = forms.CharField(max_length=20)
    last_name = forms.CharField(max_length=20)
    email = forms.CharField(max_length=50,
                            widget=forms.EmailInput())
    username = forms.CharField(max_length=20)
    password = forms.CharField(max_length=200,
                               label='Password',
                               widget=forms.PasswordInput())
    confirm_password = forms.CharField(max_length=200,
                                       label='Confirm password',
                                       widget=forms.PasswordInput())

    # Customizes form validation for properties that apply to more
    # than one field.  Overrides the forms.Form.clean function.
    def clean(self):
        # Calls our parent (forms.Form) .clean function, gets a dictionary
        # of cleaned data as a result
        cleaned_data = super().clean()

        # Confirms that the two password fields match
        password1 = cleaned_data.get('password')
        password2 = cleaned_data.get('confirm_password')
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords did not match.")

        # We must return the cleaned data we got from our parent.
        return cleaned_data

    # Customizes form validation for the username field.
    def clean_username(self):
        # Confirms that the username is not already present in the
        # User model database.
        username = self.cleaned_data.get('username')
        if User.objects.filter(username__exact=username):
            raise forms.ValidationError("Username is already taken.")

        # We must return the cleaned data we got from the cleaned_data
        # dictionary
        return username

    def clean_password(self):
        # Calls our parent (forms.Form) .clean function, gets a dictionary
        # of cleaned data as a result
        cleaned_data = super().clean()

        # Confirms that the two password fields match
        password1 = cleaned_data.get('password')
        password2 = cleaned_data.get('confirm_password')
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords did not match.")

        # We must return the cleaned data we got from our parent.
        return password1

    def clean_confirm_password(self):
        # Calls our parent (forms.Form) .clean function, gets a dictionary
        # of cleaned data as a result
        cleaned_data = super().clean()

        # Confirms that the two password fields match
        password1 = cleaned_data.get('password')
        password2 = cleaned_data.get('confirm_password')
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords did not match.")

        # We must return the cleaned data we got from our parent.
        return password2


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('profile_picture',)
        labels = {
            'profile_picture': 'Profile Picture:'
        }

    def clean(self):
        cleaned_data = super().clean()
        picture = cleaned_data['profile_picture']
        print(picture)
        if not picture or not hasattr(picture, 'content_type'):
            raise forms.ValidationError('You must upload a picture')
        if not picture.content_type or not picture.content_type.startswith('image'):
            raise forms.ValidationError('File type is not image')
        return cleaned_data

hw7/socialnetwork/views.py
from django.db.models import FileField
from django.http import Http404, HttpResponse
from django.shortcuts import render, get_object_or_404
from django.shortcuts import render, redirect
from django.urls import reverse

from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout

from django.utils import timezone

from socialnetwork.forms import LoginForm, RegisterForm

from socialnetwork.models import Post, Profile

from socialnetwork.forms import ProfileForm

from socialnetwork.models import Client

from socialnetwork.models import Comment

import json
# Create your views here.
def login_action(request):
    context = {}
    if request.method == 'GET':
        form = LoginForm()
        context['form'] = form
        return render(request, 'socialnetwork/login.html', context)
    form = LoginForm(request.POST)
    context['form'] = form
    if not form.is_valid():
        return render(request, 'socialnetwork/login.html', context)
    new_user = authenticate(username=form.cleaned_data['username'],
                            password=form.cleaned_data['password'])

    login(request, new_user)
    return redirect(reverse('home'))


def logout_action(request):
    logout(request)
    return redirect(reverse('login'))


def register_action(request):
    context = {}
    if request.method == 'GET':
        form = RegisterForm()
        context['form'] = form
        return render(request, 'socialnetwork/register.html', context)
    # Creates a bound form from the request POST parameters and makes the
    # form available in the request context dictionary.
    form = RegisterForm(request.POST)
    context['form'] = form

    # Validates the form.
    if not form.is_valid():
        return render(request, 'socialnetwork/register.html', context)

    # At this point, the form data is valid.  Register and login the user.

    new_user = User.objects.create_user(username=form.cleaned_data['username'],
                                        password=form.cleaned_data['password'],
                                        email=form.cleaned_data['email'],
                                        first_name=form.cleaned_data['first_name'],
                                        last_name=form.cleaned_data['last_name'])
    new_user.save()

    new_user = authenticate(username=form.cleaned_data['username'],
                            password=form.cleaned_data['password'])
    login(request, new_user)
    profile = Profile(user=request.user)
    profile.save()
    client = Client(user=request.user)
    client.save()
    return redirect(reverse('home'))


@login_required
def global_stream_action(request):
    context = {}
    name = request.user.first_name + " " + request.user.last_name
    context['name'] = name
    user = request.user
    if request.method == 'GET':
        posts = Post.objects.all().order_by('-date')
        context['posts'] = posts
        return render(request, 'socialnetwork/global_stream.html', context)
    if request.method == 'POST':
        content = request.POST["new_post"]
        post = Post(author=user, content=content)
        post.save()
        return redirect('global_stream')


def follower_stream_action(request):
    context = {}
    name = request.user.first_name + " " + request.user.last_name
    context['name'] = name
    user = request.user
    client = Client.objects.filter(user__id=user.id)[0]
    followings = client.followings.all()
    if request.method == 'GET':
        posts_ = Post.objects.all().order_by('-date')
        posts = []
        for post in posts_:
            if followings.contains(post.author):
                posts.append(post)
        context['posts'] = posts
        return render(request, 'socialnetwork/follower_stream.html', context)
    if request.method == 'POST':
        content = request.POST["new_post"]
        post = Post(author=user, content=content)
        post.save()
        return redirect('follower_stream')


def my_profile_action(request):
    context = {}
    user = request.user
    profile = Profile.objects.filter(user__id=user.id)[0]
    name = user.first_name + " " + user.last_name
    context['name'] = name
    context['bio'] = profile.bio
    context['profile_id'] = profile.id

    client = Client.objects.filter(user__id=user.id)[0]
    followings = client.followings.all()
    context['followings'] = followings
    # followings = []
    # for f_client in followings_client:
    #     followings.append(f_client.user)
    if request.method == 'GET':
        context['form'] = ProfileForm
        if not profile.profile_picture:
            context['hasPicture'] = False
        else:
            context['hasPicture'] = True
        return render(request, 'socialnetwork/my_profile.html', context)
    else:
        form = ProfileForm(request.POST, request.FILES)
        if not form.is_valid():
            context['form'] = form
            context['hasPicture'] = False
            return render(request, 'socialnetwork/my_profile.html', context)
        else:
            pic = form.cleaned_data['profile_picture']
            profile.profile_picture = pic
            profile.content_type = pic.content_type
            profile.bio = request.POST['bio']
            profile.save()
            context['form'] = ProfileForm
            context['hasPicture'] = True
            # return render(request, 'socialnetwork/my_profile.html', context)
            return redirect('my_profile')


# id is userid
def personal_profile_action(request, id):
    context = {}
    user = User.objects.filter(id=id)[0]
    my_user = request.user
    context['my_name'] = my_user.first_name+" "+my_user.last_name
    profile = Profile.objects.filter(user__id=user.id)[0]
    context['profile_id'] = profile.id
    if not profile.profile_picture:
        context['hasPicture'] = False
    else:
        context['hasPicture'] = True
    if my_user.id == id:
        return my_profile_action(request)
    profile = Profile.objects.filter(user__id=id)[0]
    name = user.first_name + " " + user.last_name
    context['name'] = name
    context['bio'] = profile.bio
    context['id'] = user.id
    client = Client.objects.filter(user__id=my_user.id)[0]

    if request.method == 'GET':
        context['picture'] = profile.profile_picture
        if client.followings.contains(user):
            context['isFollowing'] = True
        else:
            context['isFollowing'] = False
        return render(request, 'socialnetwork/personal_profile.html', context)
    else:
        if client.followings.contains(user):
            client.followings.remove(user)
        else:
            client.followings.add(user)
        return redirect('personal_profile', id=user.id)



    # else:
    #     print(request.POST['unfollow'])
    #     if request.POST['follow']:
    #         client.followings.add(user)
    #         context['isFollowing'] = True
    #     if request.POST['unfollow']:
    #         client.followings.remove(user)
    #         context['isFollowing'] = False
    #     print(context['isFollowing'])
    #     return redirect('personal_profile/'+id)

#
# def follow_unfollow(request, id1, id2):
#     user2 = User.objects.filter(id=id2)[0]
#     client = Client.objects.filter(user__id=id1)[0]
#     if client.followings.contains(user2):
#         client.followings.remove(user2)
#     else:
#         client.followings.add(user2)
#     return redirect('personal_profile/' + id2)


# id is userid
def get_photo_action(request, id):
    profile = get_object_or_404(Profile, id=id)
    if not profile.profile_picture:
        raise Http404
    return HttpResponse(profile.profile_picture, content_type=profile.content_type)



def json_dumps_serializer_global(request):
    if not request.user.id:
        return error_resp_json("You are not logged in", status=401)
    response_content = []
    for post in Post.objects.all().order_by('-date'):
        comments = []
        for comment in Comment.objects.filter(post__id=post.id).all().order_by('-date'):
            comment_item = {
                'id': comment.id,
                'texts': comment.content,
                'date': comment.date.isoformat(),
                'post_id': comment.post.id,
                'comment_first_name': comment.author.first_name,
                'comment_last_name': comment.author.last_name,
                'author_id': comment.author.id,
            }
            comments.append(comment_item)
        post_item = {
            'id': post.id,
            'texts': post.content,
            'first_name': post.author.first_name,
            'last_name': post.author.last_name,
            'author_id': post.author.id,
            'comments': comments,
            'date': post.date.isoformat(),
        }
        response_content.append(post_item)

    json_resp = json.dumps(response_content)

    return HttpResponse(json_resp, content_type='application/json')


def json_dumps_serializer_follower(request):
    if not request.user.id:
        return error_resp_json("You must be logged in to do this operation", status=401)
    response_data = []
    user = request.user
    # find the user and then get all the followers.
    client = Client.objects.filter(user__id=user.id)[0]
    followings = client.followings.all()
    for post in Post.objects.all().order_by('-date'):
        if not followings.contains(post.author):
            continue
        comments = []
        for comment in Comment.objects.filter(post__id=post.id).all().order_by('-date'):
            comment_item = {
                'id': comment.id,
                'texts': comment.content,
                'date': comment.date.isoformat(),
                'post_id': comment.post.id,
                'comment_first_name': comment.author.first_name,
                'comment_last_name': comment.author.last_name,
                'author_id': comment.author.id,
            }

hw7/socialnetwork/templates/socialnetwork/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static%}
    <link href="{% static 'socialnetwork/base.css' %}" rel="stylesheet" type="text/css">
    <script src="{% static 'socialnetwork.js' %}" type="text/javascript"></script>
    <title> {% block title %} Social Network {% endblock %} </title>
</head>
<body>
    <div class = 'head' id="id_header_div">
        <div class="big-heading" id="id_site_name">
			Blog Master
		</div>
	    <div class="user-info">
			{% block user-info %}
			{% endblock %}
	    </div>
    </div>

    <div class="page" id="id_page_name">
        {% block page %}
        {% endblock %}
    </div>
    <div class="content">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

hw7/socialnetwork/templates/socialnetwork/follower_stream.html
{% extends "socialnetwork/base.html" %}

{% block user-info %}
    <div>
        <a href="{% url 'my_profile' %}" id="id_nav_profile">
            {{ name }}
        </a>
    </div>
    <div id="option">
        <div>
        <a href="{% url 'global_stream' %}" id="id_nav_global_stream">
            Global
        </a>
        </div>
        <div>
            <a href="{% url 'follower_stream' %}" id="id_nav_follower_stream">
                Follower
            </a>
        </div>
        <div>
            <a href="{% url 'logout' %}" id="id_nav_logout">
                Logout
            </a>
        </div>
    </div>
{% endblock %}

{% block page %}
Follower Stream
{% endblock %}
{% block content%}

<form method="post" action="{% url 'follower_stream' %}">
    {% csrf_token %}
</form>
    <input id="tab_type" type="hidden" class="follower">
<ul id="post_list">

</ul>
    <script>
    window.onload = getFollowerComment
    window.setInterval(getFollowerComment, 5000)
    const addCommentURL = "{% url 'add-comment' %}"
    </script>
{% endblock %}

hw7/socialnetwork/templates/socialnetwork/global_stream.html
{% extends "socialnetwork/base.html" %}

{% block user-info %}
    <div>
        <a href="{% url 'my_profile' %}" id="id_nav_profile">
            {{ name }}
        </a>
    </div>
    <div id="option">
        <div>
        <a href="{% url 'global_stream' %}" id="id_nav_global_stream">
            Global
        </a>
        </div>
        <div>
            <a href="{% url 'follower_stream' %}" id="id_nav_follower_stream">
                Follower
            </a>
        </div>
        <div>
            <a href="{% url 'logout' %}" id="id_nav_logout">
                Logout
            </a>
        </div>
    </div>
{% endblock %}

{% block page %}
Global Stream
{% endblock %}

{% block content %}
    <form method="post" action="{% url 'global_stream' %}">
        <label for="id_post_input_text">New Post:</label>
        <input type="text" name="new_post" id="id_post_input_text">

        <button type="submit" id="id_post_button">Submit</button>
        {% csrf_token %}
    </form>
    <input id="tab_type" type="hidden">
    <ul id="post_list">
    </ul>


    <script>
    window.onload = getGlobalComment
    window.setInterval(getGlobalComment, 5000)
    const addCommentURL = "{% url 'add-comment' %}"
    </script>
{% endblock %}

hw7/socialnetwork/templates/socialnetwork/login.html
{% extends "socialnetwork/base.html" %}

{% block user-info %}
    <div >
        <a id = "id_register_link" href="{% url 'register' %}">
            Register
        </a>
    </div>
{% endblock %}

{% block page %}
Login
{% endblock %}

{% block content%}
    <p>Login to the social network:</p>
    <form method="post" action="{% url 'login' %}">
        <table>
            {{form}}
        </table>
        {% csrf_token %}
        <button type="submit" id="id_login_button">Submit</button>
    </form>
{% endblock %}

hw7/socialnetwork/templates/socialnetwork/my_profile.html
{% extends "socialnetwork/base.html" %}

{% block user-info %}
    <div>
        <a href="{% url 'my_profile' %}" id="id_nav_profile">
            {{ name }}
        </a>
    </div>
    <div id="option">
        <div>
        <a href="{% url 'global_stream' %}" id="id_nav_global_stream">
            Global
        </a>
        </div>
        <div>
            <a href="{% url 'follower_stream' %}" id="id_nav_follower_stream">
                Follower
            </a>
        </div>
        <div>
            <a href="{% url 'logout' %}" id="id_nav_logout">
                Logout
            </a>
        </div>
    </div>
{% endblock %}

{% block page %}
Profile page for {{ name }}
{% endblock %}

{% block content%}
    {% load static%}
    {% if hasPicture %}
        <img id="id_user_picture" src="{% url 'photo' profile_id %}"><br>
    {% endif %}
    {% if not hasPicture %}
        <img id="id_user_picture" src="{% static 'profile.jpg' %}"><br>
    {% endif %}
    <form enctype="multipart/form-data" action="{% url 'my_profile' %}" method="POST">
        <textarea id="id_bio_input_text" name="bio" >{{ bio }}</textarea><br>
        {{ form }}
{#        Profile Picture:<input type="file" id="id_profile_picture" name="picture"><br>#}
        <button type="submit" id="id_update_profile_button">Submit</button>
    {% csrf_token %}
    </form>
    You are following:<br>
    {% for following in followings %}
        <a href="{% url 'personal_profile' following.id%}" id="id_profile_link_{{ following.username }}">{{ following.first_name }} {{ following.last_name }}</a>
    {% endfor %}
{#    <a href="{% url 'personal_profile' %}" id="id_profile_link_1">Farnam Jahanian</a>#}
{% endblock %}

hw7/socialnetwork/templates/socialnetwork/personal_profile.html
{% extends "socialnetwork/base.html" %}

{% block user-info %}
    <div>
        <a href="{% url 'my_profile' %}" id="id_nav_profile">
            {{ my_name }}
        </a>
    </div>
    <div id="option">
        <div>
        <a href="{% url 'global_stream' %}" id="id_nav_global_stream">
            Global
        </a>
        </div>
        <div>
            <a href="{% url 'follower_stream' %}" id="id_nav_follower_stream">
                Follower
            </a>
        </div>
        <div>
            <a href="{% url 'logout' %}" id="id_nav_logout">
                Logout
            </a>
        </div>
    </div>
{% endblock %}

{% block page %}
Profile page for {{ name }}
{% endblock %}

{% block content%}
    {% load static%}
{#    <img id="id_user_picture" src="{% static 'profile.jpg' %}"><br>#}
    {% if hasPicture %}
        <img id="id_user_picture" src="{% url 'photo' profile_id %}"><br>
    {% endif %}
    {% if not hasPicture %}
        <img id="id_user_picture" src="{% static 'profile.jpg' %}"><br>
    {% endif %}
    <textarea id="id_user_bio" readonly>{{ bio }}</textarea><br>
    <form action="{% url 'personal_profile' id%}" method="POST">
        {% if isFollowing %}
            <button type="submit" id="id_unfollow" name="unfollow">Unfollow</button>
{#        {% endif %}#}
        {% else %}
            <button type="submit" id="id_follow" name="follow">Follow</button>
        {% endif %}
{#    {{ isFollowing }}#}
    {% csrf_token %}
    </form>
{% endblock %}

hw7/socialnetwork/templates/socialnetwork/register.html
{% extends "socialnetwork/base.html" %}

{% block user-info %}
    <div>
        <a id="id_login_link" href="{% url 'login' %}">
            login
        </a>
    </div>
{% endblock %}

{% block page %}
Register
{% endblock %}

{% block content %}
    <p>Register for the social network:</p>

    <form method="post" action="{% url 'register' %}">
        <table>
            {% for field in form.visible_fields %}
                <tr>
                    <td>{{field.label_tag}}</td>
                    <td>{{field}}</td>
                    <td class="errorlist">
                        {% for error in field.errors %} {{error}} {% endfor %}
                    </td>
                </tr>
            {% endfor %}
        </table>
        {% csrf_token %}
        <button type="submit" id="id_register_button">Register</button>
    </form>

{#    {% for error in form.non_field_errors %}#}
{#        <p class="error">#}
{#            {{ error }}#}
{#        </p>#}
{#    {% endfor %}#}

{% endblock %}